apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatformservice
  template:
    metadata:
      labels:
        app: flatformservice
    spec:
      containers:
        - name: flatformservice
          image: becomerichman/flatformservice:latest